name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: download-arin
      run: python ./ftp-s3-sync/src/update_ftp_file.py --source "ftp://ftp.arin.net/pub/rr/arin.db" --name "arin.db" --target $(pwd)/dist
